default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ENV["sqlpassword"]
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: aatms_development
